### ISSUE TITLE
Add tasks for Receiver

### ISSUE THREAD

**Issue by amashi996** [assignments-sliit/procsupport-backend#17]
- [x] view POs pending deliveries
- [x] create deliveries for Purchased Orders
- [x] track the progress of deliveries
- [ ] get an invoice from purchased for each purchased order

**Comment by polroti** [comment]
POs pending delivery = ones in INVOICED

**Comment by polroti** [comment]
get an invoice from purchased for each purchased order

--meka ba krnna
